// Purpose: Integration testbench for aes_gcm_top — encrypt / decrypt / tamper
// Author: Claude
// Date: 2026-05-25
//
// Three phases (all self-checking against Python golden vectors):
//   Phase 1 — ENCRYPT: 14 blocks, streaming producer model, compare all 14
//             ciphertext blocks and tag against tb/vectors/.
//   Phase 2 — DECRYPT: feed golden CT + tag, compare recovered PT and tag_ok_o.
//   Phase 3 — TAMPER:  flip CT[0] bit 0, verify tag_ok_o=0.
//
// STREAMING PRODUCER MODEL: on the cycle cipher_data_in_valid_i &&
// cipher_data_in_ready_o are both high, the FSM consumes the block.  The
// NEXT cycle we present the following block (or 'x if none remain).  This
// models a real FIFO — the bus is NOT held stable past the handshake.
// If the DUT's combinational XOR path requires plaintext to be stable until
// AES completes, the CT comparison WILL fail; that is reported, not hidden.
//
// Golden constants come ONLY from scripts/gen_gcm_vectors.py output.
// Run `python3 scripts/gen_gcm_vectors.py` to regenerate the vectors.

`timescale 1ns/1ps

module tb_aes_gcm_top;

  // Default geometry of aes_gcm_top (AES-128, 256-byte page)
  localparam int KEY_W  = 128;
  localparam int IV_W   = 96;
  localparam int TAG_W  = 128;
  localparam int DATA_W = 128;
  localparam int AAD_W  = 128;

  localparam int CLK_HALF = 5;   // 10 ns period
  localparam int NBLOCKS  = 14;

  // -------------------------------------------------------------------------
  // DUT ports
  // -------------------------------------------------------------------------
  logic         clk_i, rst_ni;
  logic         start_i, encdec_i;
  logic [127:0] key_i, aad_i, exp_tag_i;
  logic  [95:0] iv_i;
  logic [127:0] cipher_plaintext_data_i;
  logic [127:0] cipher_spi_data_i;
  logic         aad_valid_i;
  logic         aad_ready_o;
  logic         data_valid_i;
  logic         data_ready_o;
  logic [127:0] cipher_data_out_o;
  logic         cipher_data_out_valid_o;
  logic         done_o;
  logic         tag_ok_o;
  // Ports not under test
  logic         key_consumed_nc, key_ready_nc, busy_nc, err_nc;
  logic         data_out_last_nc;
  logic         rsp_ready_i;
  logic         page_done_nc;
  logic [4:0]   total_blocks_nc;
  logic [3:0]   state_nc;

  // -------------------------------------------------------------------------
  // DUT
  // -------------------------------------------------------------------------
  aes_gcm_top dut (
    .clk_i                    (clk_i),
    .rst_ni                   (rst_ni),
    .cmd_valid_i             (start_i),
    .cmd_ready_o             (aad_ready_o),
    .cmd_mode_i              (encdec_i),
    .cmd_key_i               (key_i),
    .cmd_iv_i                (iv_i),
    .cmd_aad_i               (aad_i),
    .cmd_exp_tag_i           (exp_tag_i),
    .data_in_valid_i         (data_valid_i),
    .data_in_ready_o         (data_ready_o),
    .data_in_i               (encdec_i ? cipher_plaintext_data_i : cipher_spi_data_i),
    .data_out_o              (cipher_data_out_o),
    .data_out_valid_o        (cipher_data_out_valid_o),
    .data_out_ready_i        (1'b1),
    .rsp_valid_o             (done_o),
    .rsp_ready_i             (rsp_ready_i),
    .rsp_auth_ok_o           (tag_ok_o),
    .rsp_error_o             (err_nc),
    .data_out_last_o         (data_out_last_nc)
  );

  assign key_consumed_nc = start_i && aad_ready_o;
  assign key_ready_nc    = aad_ready_o;
  assign busy_nc         = !aad_ready_o;
  assign page_done_nc    = done_o;
  assign total_blocks_nc = encdec_i ? 5'd16 : 5'd14;
  assign state_nc        = '0;

  // Clock
  initial clk_i = 1'b0;
  always  #CLK_HALF clk_i = ~clk_i;

  int pass_count, fail_count;

  // -------------------------------------------------------------------------
  // Test parameters — match scripts/gen_gcm_vectors.py
  // -------------------------------------------------------------------------
  localparam logic [127:0] GCM_KEY = 128'h2b7e151628aed2a6abf7158809cf4f3c;
  localparam logic  [95:0] GCM_IV  = 96'hcafebabe_facedbad_decaf888;
  localparam logic [127:0] GCM_AAD = 128'hfeedface_deadbeef_feedface_deadbeef;

  // -------------------------------------------------------------------------
  // Golden vectors loaded from tb/vectors/ (generated by Python script)
  // -------------------------------------------------------------------------
  logic [127:0] golden_ct  [NBLOCKS];
  logic [127:0] golden_tag_arr [1];
  logic [127:0] golden_tag;

  // Plaintext: byte[i] = i & 0xff  → P[j] = {j*16, j*16+1, ..., j*16+15}
  logic [127:0] P [NBLOCKS];

  // Captured outputs
  logic [127:0] ct_got    [NBLOCKS];
  logic [127:0] pt_got    [NBLOCKS];
  logic [127:0] ct_tamper [NBLOCKS];
  logic         rsp_seen;
  logic         rsp_auth_ok_got;

  // -------------------------------------------------------------------------
  // Cycle accounting
  // -------------------------------------------------------------------------
  longint unsigned cycle_count;
  logic            timing_active;
  logic            timing_encrypt;
  int signed       timing_start_cycle;
  int signed       timing_key_cycle;
  int signed       timing_aad_cycle;
  int signed       timing_done_cycle;
  int signed       timing_page_done_cycle;
  int signed       timing_input_cycle  [NBLOCKS];
  int signed       timing_output_cycle [NBLOCKS + 2];
  int               timing_input_count;
  int               timing_output_count;

  always @(posedge clk_i) begin
    cycle_count = cycle_count + 1;

    if (timing_active) begin
      if (start_i && timing_start_cycle < 0)
        timing_start_cycle = cycle_count;

      if (key_consumed_nc && timing_key_cycle < 0)
        timing_key_cycle = cycle_count;

      if (aad_valid_i && aad_ready_o && timing_aad_cycle < 0)
        timing_aad_cycle = cycle_count;

      if (data_valid_i && data_ready_o && timing_input_count < NBLOCKS) begin
        timing_input_cycle[timing_input_count] = cycle_count;
        timing_input_count++;
      end

      if (cipher_data_out_valid_o && timing_output_count < NBLOCKS + 2) begin
        timing_output_cycle[timing_output_count] = cycle_count;
        timing_output_count++;
      end

      if (done_o && timing_done_cycle < 0)
        timing_done_cycle = cycle_count;

      if (page_done_nc && timing_page_done_cycle < 0)
        timing_page_done_cycle = cycle_count;
    end
  end

  // -------------------------------------------------------------------------
  // Initialise plaintext and load golden vectors
  // -------------------------------------------------------------------------
  initial begin
    cycle_count   = 0;
    timing_active = 1'b0;

    for (int j = 0; j < NBLOCKS; j++) begin
      logic [127:0] blk;
      blk = '0;
      for (int k = 0; k < 16; k++)
        blk = (blk << 8) | 8'((j * 16 + k) & 8'hff);
      P[j] = blk;
    end

    $readmemh("tb/vectors/ct.hex",  golden_ct);
    $readmemh("tb/vectors/tag.hex", golden_tag_arr);
    golden_tag = golden_tag_arr[0];
  end

  // -------------------------------------------------------------------------
  // Tasks
  // -------------------------------------------------------------------------
  task automatic timing_start(input logic is_encrypt);
    timing_active         = 1'b0;
    timing_encrypt        = is_encrypt;
    timing_start_cycle    = -1;
    timing_key_cycle      = -1;
    timing_aad_cycle      = -1;
    timing_done_cycle     = -1;
    timing_page_done_cycle = -1;
    timing_input_count    = 0;
    timing_output_count   = 0;
    for (int i = 0; i < NBLOCKS; i++) begin
      timing_input_cycle[i]  = -1;
      timing_output_cycle[i] = -1;
    end
    timing_output_cycle[NBLOCKS]     = -1;
    timing_output_cycle[NBLOCKS + 1] = -1;
    timing_active = 1'b1;
  endtask

  task automatic timing_report(input string name);
    int latency_sum;
    int latency_min;
    int latency_max;
    int input_gap_sum;
    int input_gap_min;
    int input_gap_max;
    int output_gap_sum;
    int output_gap_min;
    int output_gap_max;
    int operation_cycles;
    real operation_us_100mhz;
    real payload_mbps_100mhz;

    timing_active = 1'b0;
    latency_sum = 0;
    latency_min = 32'h7fff_ffff;
    latency_max = 0;
    input_gap_sum = 0;
    input_gap_min = 32'h7fff_ffff;
    input_gap_max = 0;
    output_gap_sum = 0;
    output_gap_min = 32'h7fff_ffff;
    output_gap_max = 0;

    for (int i = 0; i < NBLOCKS; i++) begin
      int block_latency;
      block_latency = timing_output_cycle[i] - timing_input_cycle[i];
      latency_sum += block_latency;
      if (block_latency < latency_min)
        latency_min = block_latency;
      if (block_latency > latency_max)
        latency_max = block_latency;

      if (i > 0) begin
        int input_gap;
        int output_gap;
        input_gap = timing_input_cycle[i] - timing_input_cycle[i - 1];
        output_gap = timing_output_cycle[i] - timing_output_cycle[i - 1];
        input_gap_sum += input_gap;
        output_gap_sum += output_gap;
        if (input_gap < input_gap_min)
          input_gap_min = input_gap;
        if (input_gap > input_gap_max)
          input_gap_max = input_gap;
        if (output_gap < output_gap_min)
          output_gap_min = output_gap;
        if (output_gap > output_gap_max)
          output_gap_max = output_gap;
      end
    end

    operation_cycles = timing_encrypt
        ? timing_page_done_cycle - timing_start_cycle
        : timing_done_cycle - timing_start_cycle;
    operation_us_100mhz = operation_cycles / 100.0;
    payload_mbps_100mhz = 224.0 / operation_us_100mhz;

    $display("");
    $display("--- TIMING REPORT: %s ---", name);
    $display("  start -> key consumed       : %0d cycles",
             timing_key_cycle - timing_start_cycle);
    $display("  start -> AAD accepted       : %0d cycles",
             timing_aad_cycle - timing_start_cycle);
    $display("  start -> first input        : %0d cycles",
             timing_input_cycle[0] - timing_start_cycle);
    $display("  first input -> first output : %0d cycles",
             timing_output_cycle[0] - timing_input_cycle[0]);
    $display("  payload block latency       : min=%0d max=%0d avg=%0.2f cycles",
             latency_min, latency_max, latency_sum / 14.0);
    $display("  input acceptance interval   : min=%0d max=%0d avg=%0.2f cycles",
             input_gap_min, input_gap_max, input_gap_sum / 13.0);
    $display("  output transfer interval    : min=%0d max=%0d avg=%0.2f cycles",
             output_gap_min, output_gap_max, output_gap_sum / 13.0);
    $display("  first input -> last payload : %0d cycles",
             timing_output_cycle[NBLOCKS - 1] - timing_input_cycle[0]);
    $display("  last payload -> done_o      : %0d cycles",
             timing_done_cycle - timing_output_cycle[NBLOCKS - 1]);
    $display("  start -> done_o             : %0d cycles",
             timing_done_cycle - timing_start_cycle);
    $display("  start -> page_done_o        : %0d cycles",
             timing_page_done_cycle - timing_start_cycle);
    if (timing_encrypt) begin
      $display("  done_o -> tag transfer      : %0d cycles",
               timing_output_cycle[NBLOCKS] - timing_done_cycle);
      $display("  done_o -> AAD/page_done     : %0d cycles",
               timing_page_done_cycle - timing_done_cycle);
    end
    $display("  documented operation        : %0d cycles = %0.2f us at 100 MHz",
             operation_cycles, operation_us_100mhz);
    $display("  useful-payload throughput   : %0.3f MB/s at 100 MHz",
             payload_mbps_100mhz);
    $display("  accepted inputs/outputs     : %0d / %0d",
             timing_input_count, timing_output_count);
  endtask

  task automatic reset_dut;
    rst_ni                  = 1'b0;
    start_i                 = 1'b0;
    encdec_i                = 1'b1;
    key_i                   = '0;
    iv_i                    = '0;
    aad_i                   = '0;
    exp_tag_i               = '0;
    aad_valid_i             = 1'b0;
    data_valid_i            = 1'b0;
    rsp_ready_i             = 1'b0;
    rsp_seen                = 1'b0;
    rsp_auth_ok_got         = 1'b0;
    cipher_plaintext_data_i = '0;
    cipher_spi_data_i       = '0;
    repeat (4) @(posedge clk_i);
    #1;
    rst_ni = 1'b1;
    @(posedge clk_i);
    #1;
  endtask

  task automatic chk_bit(input string name, input logic got, input logic exp);
    if (got === exp) begin
      $display("  PASS  %s", name);
      pass_count++;
    end else begin
      $display("  FAIL  %s  (expected %b, got %b)", name, exp, got);
      fail_count++;
    end
  endtask

  task automatic chk_vec(input string name, input logic [127:0] got,
                          input logic [127:0] exp);
    if (got === exp) begin
      $display("  PASS  %s", name);
      pass_count++;
    end else begin
      $display("  FAIL  %s", name);
      $display("          expected = %h", exp);
      $display("          got      = %h", got);
      fail_count++;
    end
  endtask

  // Kick off one GCM operation atomically, then wait for ST_PROC_PAYLOAD.
  task automatic gcm_start(input logic is_encrypt, input logic [127:0] exp_tag_p);
    @(posedge clk_i); #1;
    timing_start(is_encrypt);
    start_i     = 1'b1;
    encdec_i    = is_encrypt;
    key_i       = GCM_KEY;
    iv_i        = GCM_IV;
    aad_i       = GCM_AAD;
    exp_tag_i   = exp_tag_p;
    aad_valid_i = 1'b1;
    @(posedge clk_i iff aad_ready_o); #1;
    start_i     = 1'b0;
    aad_valid_i = 1'b0;
    while (!data_ready_o) @(posedge clk_i);
    #1;
  endtask

  // Drive 14 blocks with a streaming-FIFO producer model and collect outputs.
  //
  // Producer: on the cycle valid && ready are both high, the handshake is done.
  //   The NEXT cycle we put block[i+1] on the bus (or 'x for the last block).
  //   We do NOT hold block[i] stable past its handshake cycle.
  //
  // Capture: sample cipher_data_out_o on every cipher_data_out_valid_o pulse.
  //   That pulse fires when aes_valid_i goes high in ST_PROC_PAYLOAD.  At that
  //   moment cipher_data_out_o = AES(K,ctr_i) XOR <current plaintext bus>.
  //   With the streaming model the bus has already advanced to block[i+1], so
  //   the XOR is with the wrong word — the capture faithfully records what the
  //   DUT actually produced, then the chk_vec call exposes any mismatch.
  task automatic run_payload(
    input  logic [127:0] blk_in  [NBLOCKS],
    output logic [127:0] blk_out [NBLOCKS]
  );
    automatic int drive_idx = 0;
    automatic int cap_idx   = 0;

    fork
      // ------------------------------------------------------------------
      // Thread 1: streaming producer
      // ------------------------------------------------------------------
      begin : t_drive
        while (drive_idx < NBLOCKS) begin
          // Wait for the FSM to signal ready for the next block
          while (!data_ready_o) @(posedge clk_i);
          #1;
          // Present block[drive_idx] and assert valid this cycle
          cipher_plaintext_data_i = blk_in[drive_idx];
          cipher_spi_data_i       = blk_in[drive_idx];
          data_valid_i = 1'b1;
          @(posedge clk_i); #1;  // handshake happens at this rising edge
          // Streaming model: advance bus IMMEDIATELY to next block
          drive_idx++;
          data_valid_i = 1'b0;
          if (drive_idx < NBLOCKS) begin
            cipher_plaintext_data_i = blk_in[drive_idx];
            cipher_spi_data_i       = blk_in[drive_idx];
          end else begin
            cipher_plaintext_data_i = 'x;
            cipher_spi_data_i       = 'x;
          end
        end
      end : t_drive

      // ------------------------------------------------------------------
      // Thread 2: output capture on cipher_data_out_valid_o strobe
      // ------------------------------------------------------------------
      begin : t_capture
        while (cap_idx < NBLOCKS) begin
          @(posedge clk_i);
          if (cipher_data_out_valid_o && 1'b1)
            blk_out[cap_idx++] = cipher_data_out_o;
        end
      end : t_capture
    join

    // Wait for the response pulse after FINALIZE and output drain complete.
    @(posedge done_o);
    #1;
    rsp_seen        = done_o;
    rsp_auth_ok_got = tag_ok_o;
    rsp_ready_i = 1'b1;
    @(posedge clk_i);
    #1;
    rsp_ready_i = 1'b0;
  endtask

  // -------------------------------------------------------------------------
  // Stimulus
  // -------------------------------------------------------------------------
  initial begin
    pass_count = 0;
    fail_count = 0;
    $display("=== tb_aes_gcm_top: AES-128-GCM integration (14-block) ===");
    $display("KEY = %h", GCM_KEY);
    $display("IV  = %h", GCM_IV);
    $display("AAD = %h", GCM_AAD);
    $display("PT  = bytes(range(240))");
    $display("");

    reset_dut();

    // =====================================================================
    // Phase 1 — ENCRYPT
    // =====================================================================
    $display("--- Phase 1: ENCRYPT ---");
    gcm_start(1'b1, 128'h0);
    run_payload(P, ct_got);
    timing_report("ENCRYPT, always ready");

    for (int i = 0; i < NBLOCKS; i++)
      chk_vec($sformatf("CT[%02d]", i), ct_got[i], golden_ct[i]);

    chk_bit("rsp_valid_o observed", rsp_seen, 1'b1);

    // =====================================================================
    // Phase 2 — DECRYPT (valid ciphertext + golden tag)
    // =====================================================================
    $display("");
    $display("--- Phase 2: DECRYPT (valid CT + golden tag) ---");
    reset_dut();
    gcm_start(1'b0, golden_tag);
    run_payload(ct_got, pt_got);
    timing_report("DECRYPT, always ready");

    for (int i = 0; i < NBLOCKS; i++)
      chk_vec($sformatf("PT_dec[%02d]", i), pt_got[i], P[i]);

    chk_bit("rsp_auth_ok_o = 1 (authenticated)", rsp_auth_ok_got, 1'b1);

    // =====================================================================
    // Phase 3 — TAMPER (flip CT[0] LSB, must reject)
    // =====================================================================
    $display("");
    $display("--- Phase 3: TAMPER (CT[0] bit 0 flipped) ---");
    foreach (ct_tamper[i]) ct_tamper[i] = ct_got[i];
    ct_tamper[0] ^= 128'h1;

    reset_dut();
    gcm_start(1'b0, golden_tag);
    run_payload(ct_tamper, pt_got);

    chk_bit("rsp_auth_ok_o = 0 (tamper detected)", rsp_auth_ok_got, 1'b0);

    // =====================================================================
    // Summary
    // =====================================================================
    $display("");
    $display("=== %0d passed, %0d failed ===", pass_count, fail_count);
    if (fail_count == 0)
      $display("ALL TESTS PASSED");
    else
      $display("TESTS FAILED");

    $finish;
  end

  // Watchdog: 3 runs × (key-expand ~170 + H/EJ0 2×53 + AAD-GHASH 128
  //           + 15 × (AES 53 + GHASH 128) + finalize 130) ≈ 3 × 3500 cycles
  initial begin
    #5_000_000;
    $display("TIMEOUT — simulation did not finish");
    $finish;
  end

endmodule
